#!/bin/bash

clear

echo "------------- Script to for Die2Sim ---------------"

cd build
cmake .. && \
make && \
cd ../
# ./build/Die2Sim -c
./build/Die2Sim -j ./data/USC_new/KSA4_route.def

echo "------------------ Script ended -------------------"